server:
  port: 8080
  servlet:
    context-path: /good-lodging
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/good-lodging"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "H+FtQksllnPVgdl7v1ERls5/x/cAY7YKnRqKY1eekYrKYF0ktPHqjul8sSdrsBaY"
  valid-duration: 60 #seconds
  refreshable-duration: 120 # seconds